src-d/gitbase-web

README.md, server/handler/query_test.go
Part of #2.
Depends on #8, the only new commit is c58000f.
The tests require a working gitbase server and bblfshd server. gitbase should be serving at least this repo (https://github.com/src-d/gitbase-playground).
This will be added to the travis conf in the future, but meanwhile it can be done manually:
```bash
docker run -d --name bblfshd --privileged -p 9432:9432 -v /var/lib/bblfshd:/var/lib/bblfshd bblfsh/bblfshd
docker exec -it bblfshd bblfshctl driver install --all
go run cli/gitbase/main.go server --git=repos -v
```
=> Tests for query handler

docs/rest-api.md, server/handler/query_test.go, server/handler/tables.go, server/handler/tables_test.go, server/router.go
Part of #2.
Depends on #8 & #10, the only new commit is f33a052.
=> New endpoint get /tables

server/common_test.go, server/handler/query.go, server/handler/query_test.go, server/handler/tables.go, server/handler/tables_test.go, server/router.go, server/router_test.go, server/serializer/serializers_test.go, server/service/common.go, server/service/common_test.go
required by #1
Added tests:
- 345e890 It was added some integration tests to ensure that `/version` endpoint works,
- fe788ec It was added empty tests to get a proper coverage report,
Others:
- 86e1d6b To make the app easily testable it was used an interface of `*sql.DB`
=> Add some tests to be used by the CI

cmd/gitbase-playground/main.go, frontend/public/index.html, frontend/src/api.js, server/handler/static_files.go
Part of #4, depends on #16.
The only new commit is cec12d4.
It uses the same mechanism as code-annotation.
=>  Pass env vars from backend to frontend

Makefile, docker-compose.build.yml, docker-compose.yml, docs/quickstart-manually.md, docs/quickstart.md
If accepted it would be only needed to run:
Run latest released image:
```shell
$ GITBASEPG_REPOS_FOLDER=./repos docker-compose up
```
Run from sources (useful when developing or willing to run `tip` of `master`...)
```shell
$ GITBASEPG_REPOS_FOLDER=./repos make compose-serve
```
=> Add docker-compose

frontend/package.json, frontend/src/App.js, frontend/src/api.js, frontend/src/components/QueryBox.js, frontend/src/components/QueryBox.less, frontend/src/components/TabbedResults.less, frontend/src/setupTests.js, frontend/yarn.lock
Fixes #20.
Besides syntax highlighting this PR also adds autocomplete. To do that, the schema is loaded when the application starts. Also the query can be executed with ctrl+enter.
=> Add CodeMirror editor with sql syntax and autocomplete

Makefile, README.md, docs/quickstart-manually.md, docs/quickstart.md
Since [`docker-compose up` doesn't pull `:latest` image if it already exists locally](https://github.com/docker/compose/issues/3574) it is needed to pull it explicitly before running `docker-compose up`
As we were talking IRL I added it to the `Makefile` so it would be easier to run:
- `compose-serve-latest`: pulls `:latest` released image and serves it
- `compose-serve`: builds from current sources and serves it
Feel free to suggest any other name for `make` targets ;)
=> Force pull before running latest image

.travis.yml, server/handler/common_test.go, server/handler/query_integration_test.go, server/handler/query_uast_integration_test.go
Part of #32.
This PRs adds the already implemented integration tests to Travis CI.
The docker image `carlosms/bblfsh-ci-test:v0.0.1` contains the latest bblfshd image plus the recommended drivers (created with the [instructions here](https://github.com/bzz/ml-on-code/blob/master/images/README.md#create-bblfshd--drivers-image)). Before merging it would be better to host this image in the srcd organization.
It looks like the default gitbase port 3306 is in use in the travis image, that's why I'm using a different one.
=> Add integration tests to Travis CI

frontend/package.json, frontend/src/App.js, frontend/src/components/ResultsTable.js, frontend/src/components/ResultsTable.test.js, frontend/src/components/TabbedResults.js, frontend/src/components/__snapshots__/ResultsTable.test.js.snap, frontend/yarn.lock
=> Add code and UAST buttons in results table

Dockerfile
The binary is dynamic since we added the bblfsh API client dependency, and it won't work in alpine anymore.
New Dockerfile based on the one we use in the [bblfsh dashboard](https://github.com/bblfsh/dashboard/blob/master/Dockerfile).
=> Use debian instead of alpine for the docker container

frontend/package.json, frontend/src/App.js, frontend/src/App.less, frontend/yarn.lock
Fix: #45 
Based on #52
Currently, there is a warning
```
Warning: Failed prop type: Invalid prop `roles[0]` of type `number` supplied to `Roles`, expected `string`.
```
It will be fixed when #54 is merged.
=> Integrate uast-viewer

frontend/src/App.js, frontend/src/App.less
Fix: #47
Based on #52, #60
This PR doesn't implement syntax highlighting in editor. It requires changes to code detection (move from FE to BE) and language guessing using envy. It will be implemented in another issue: #61
=> Code viewer

frontend/src/components/TabbedResults.js, frontend/src/components/TabbedResults.less
Fix: #72 
The name is scoped to the tabbed results component. Please let me know if it should be reflected in history too.
=> Edit tab titles

frontend/public/index.html, frontend/src/App.js, frontend/src/App.less, frontend/src/components/HistoryTable.js, frontend/src/components/HistoryTable.less, frontend/src/components/QueryBox.js, frontend/src/components/QueryBox.less, frontend/src/components/ResultsTable.js, frontend/src/components/SampleQueries.less, frontend/src/components/Schema.js, frontend/src/components/Schema.less, frontend/src/components/Sidebar.js, frontend/src/components/Sidebar.less, frontend/src/components/TabbedResults.js, frontend/src/components/TabbedResults.less, frontend/src/components/__snapshots__/ResultsTable.test.js.snap, frontend/src/index.js, frontend/src/index.less, frontend/src/override.less, frontend/src/variables.less
Part of #44.
This PR adds the main styles of the design spec.
In a few places where I needed a hover effect I've chosen to set the color to 10% darker of the base color, to keep it in line with the default button hover effect.
Missing things that I'd prefer to do in separate PRs:
- Style for the CodeMirror component (main input box)
- Style for React Table (results and history tables)
- Use design spec icons instead of bootstrap glyphicons
- I left a comment in `index.html` to download and serve the fonts locally, I assume this is preferable. Thoughts on this?
cc: @ricardobaeta
=> Add main style

server/handler/static_files.go
Try to fix #70
The header is set as [No cache storage at all](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching).
=> No cache for index.html

frontend/src/components/ResultsTable.js
Fix #94.
A commit with one parent shows the hash in the table cell, with more than one parent the 'code' viewer is used.
=> Fix commit_parents showing as UAST

frontend/src/App.js
Order the left schema tables alphabetically, otherwise it's kind of random and this way looks neater.
=> Order schema tables by name

frontend/src/components/HistoryTable.js, frontend/src/components/HistoryTable.less, frontend/src/variables.less
Part of #44.
Sets colors for success & failure messages in the history table.
=> Set colors in history table

frontend/src/components/TabbedResults.less
Part of #44.
The problem, as it is in master:
With the changes in this PR:
=> Fix scroll issues in bottom panel

frontend/src/components/QueryBox.js, frontend/src/components/QueryBox.less, frontend/src/components/Sidebar.less, frontend/src/components/TabbedResults.js, frontend/src/components/TabbedResults.less
Part of #44.
Makes a few tweaks asked by @ricardobaeta:
- line height for the sidebar list items
- fixed width for the RUN QUERY button
- history tab title width adjusted to the contents.
The commit 54c1a48 was cherry-picked from #144 to avoid merge conflicts.
=> Size tweaks

frontend/src/components/DivTabs.js, frontend/src/components/TabbedResults.js, frontend/src/variables.less
Fix first 2 points in #97
The "space" problem comes from here: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/SafeAnchor.js#L61
Arrows problem comes from here: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Nav.js#L238
We can fix it by inheriting bootstrap components and disable handlers when user clicked "edit".
Please let me know if you are ok with such solution. (I'll implement in separate PR)
=> Add autofocus to tab title input

frontend/src/App.js, frontend/src/App.less, frontend/src/variables.less
Part of #44.
Sets the overall modal styles, and the fonts and colors for the code and uast viewers.
The only difference with the design spec is the code viewer font, set to monospace instead of 'source sans'.
=> Set styles for uast-viewer & modals

frontend/src/components/QueryBox.js, frontend/src/components/QueryBox.less
Part of #44.
This PR styles the SQL query input, setting the font, margins, and removing the line numbers gutter.
The `CodeMirror-gutters` style removes the gray background fron the line numbers gutter. Even if we don't use it, with this change the style matches and it can be enabled quicker at any moment.
=> Set style for the SQL query input

frontend/package.json, frontend/src/App.js, frontend/src/api.js, frontend/src/components/CodeViewer.js, frontend/src/components/CodeViewer.less, server/handler/export.go, server/handler/query.go, server/handler/uast.go, server/serializer/serializers.go, server/service/uast.go
Part of #48 
Because this issue isn't about design there are few differences that will need to fix in sequential prs:
- show uast button is located in left pane not in the title of modal (it would complicate code)
- there is no top bar on UAST (with locations, server, query) yet. The PR is big enough already. Better implement separately.
- it doesn't return underlying error from bblfsh
- list of languages is hard-coded 
- there are no workarounds for java/bash/??? yet (languageMode != language for them)
- it works freaking slow
=> Show UAST from code

frontend/src/App.js, frontend/src/App.less, frontend/src/components/QueryBox.less, frontend/src/components/Sidebar.js, frontend/src/components/Sidebar.less
Fixes #121.
Fixes the overflow problems. New `minSize` and `maxSize` to completely hide the top or bottom panels.
=> Improve split panels min & max sizes

frontend/src/App.js, frontend/src/components/QueryBox.js, frontend/src/components/QueryBox.less
Part of #44.
Implements the design spec for error messages.
Now when an error happens:
- The error message is displayed in the main query box
- The loading tab is deleted
Other change: the last success or error message is cleared when the 'run query' button is clicked.
=> Show error messages in main query box

frontend/src/components/QueryBox.js
Fix: #120
Apparently, it is broken not only in FF but in Chrome too.
=> Reload codemirror when fonts are loaded

frontend/package.json, frontend/src/components/CodeViewer.js, frontend/yarn.lock
Fix: #130 
Example of java highlighting:
Because of the lib update bug with a cursor in editor on node click is also fixed.
=> Highlighting fixes

frontend/src/App.js, frontend/src/App.less, frontend/src/components/CodeViewer.js, frontend/src/components/CodeViewer.less, frontend/src/components/Sidebar.less, frontend/src/components/TabbedResults.less, frontend/src/variables.less
Part of #48.
There is a small difference with the design spec: the blue background of the code line gutter does not carry all the way to the top.
The reason is that the width is not fixed, it depends on the number of lines, it has different widths for 1 or 3 digit line numbers. There must be a convoluted way to make it work, but I think it's not worth it, at least for now.
=> Style for the modal contents

frontend/src/components/QueryBox.less
#147
Adds the missing scroll in the main query box.
There is, however, a problem I'm not able to fix. The horizontal scroll on firefox covers half of the last line. This does not happen if CodeMirror `lineNumbers` is enabled. It might be related to https://github.com/codemirror/CodeMirror/issues/3821.
Chrome on top, firefox below it:
=> Fix missing scroll in query box

docs/quickstart.md
Fix: #39
The only place where we document `make compose-serve` is quickstart.
All requirements are already in CONTRIBUTING (including the need to put source code in GOPATH)
=> mention need to satisfy requirements to build from source

frontend/src/components/TabbedResults.js, frontend/src/components/TabbedResults.less, frontend/src/variables.less
This is my attempt to fix #145.
One possible improvement to make it easier to use with many tabs is to add tab change with the arrow keys or the mouse wheel. Actually the active tab is supposed to change with the arrow keys by default, but maybe the elements do not get focused or something...
Other improvement could be the addition of @ricardobaeta's drop down with the list of tabs next to history.
=> Shrink tab titles to fit in one line

frontend/src/components/TabbedResults.less
=> Fix tooltip vertical alignment

Makefile, docs/CONTRIBUTING.md
`make serve` now installs the frontend deps, otherwise on the latest master it results in:
```sh
$ git checkout master
$ make serve
mkdir -p build
yarn --cwd ./frontend build
yarn run v1.7.0
$ react-app-rewired build
/bin/sh: react-app-rewired: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [front-build] Error 1
```
```
$ git checkout fix-make-build
$ make serve
mkdir -p build
yarn --cwd ./frontend install
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-airbnb-base@12.1.0" has unmet peer dependency "eslint@^4.9.0".
warning " > eslint-config-airbnb-base@12.1.0" has unmet peer dependency …
```
=> Fix: make serve

frontend/src/api.js
Fix: #176 
Proxy returns error without text.
Correct headers when everything works as expected:
Headers from proxy:
As a workaround when statusText is empty I put text `${resp.code} Error` instead.
=> Correct error text for status error without text

.helm-staging.yml
Gitbase added a new `GITBASE_READONLY` flag to restrict `CREATE INDEX`: src-d/gitbase#326, tt makes sense to enable it in staging.
This uses the new changes in the chart https://github.com/src-d/charts/pull/59
=> Add GITBASE_READONLY flag to staging

Makefile
Part of #183.
`LD_FLAGS` was empty, with this PR it is evaluated when build is called and not when parsing the file
=> Fix go build args evaluation in makefile

Gopkg.lock, Makefile
Fix #203.
I also went ahead and removed `back-dependencies`, because I agree with @smacker in #160.
The dependencies are already vendored and we don't need to update them every single time we build. Now we can do a `make godep` whenever we know we need to update the dependencies.
But I will revert this last point with no problems if @bzz feels strongly about it.
=>  Makefile uses go dep releases instead of master

.travis.yml, Makefile
Fix #202, done on top of #205.
The `GO_BUILD_ARGS` has been moved because it was not being set for `make docker-build`, only for `make build`.
=> Fix footer test

frontend/package.json, frontend/src/App.js, frontend/src/api.js, frontend/src/components/TabbedResults.js, frontend/src/components/TabbedResults.less, frontend/src/setupTests.js, frontend/yarn.lock, server/handler/query.go, server/handler/query_test.go, server/handler/render.go, server/service/common.go, server/testing/common.go
Fix #199.
The abort-controller polyfill is used only for the jest tests. All major browsers apparently support AbortCotroller (https://caniuse.com/#search=fetch), and for example for older IE this PR does not break compatibility because it doesn't support fetch API either, which we already use.
I refactored the suspended tab reload to act more like a new query submit. This way the history also shows a new entry for the reload queries. In master reload actions are not reflected in the history.
Tested for chrome and firefox, please let me know if safari works as expected.
=> Cancel sql requests from the UI

server/service/logger.go
Fix #208.
It makes sense to reserve debug messages for `ENV=dev`, but info should be visible by default.
=> Change default log level to info

.drone.yml, .helm-staging.yml, .travis.yml, server/handler/export_integration_test.go
Part of #218.
Changes the repository name for drone, travis, and staging.
=> Rename to Web: update repository name in tests and staging

.drone.yml
Part of #218.
Depends on https://github.com/src-d/charts/pull/65.
@rporres: will we make any changes to these two values?
```
ingress.globalStaticIpName=gitbase-playground-staging,
ingress.hostname=gitbase-playground-staging.srcd.run
```
=> Rename to Web: helm chart

docker-compose.yml
Fix #230.
Use `latest` bblfsh image in docker-compose.
=> Update docker-compose to use latest bblfsh

.helm-staging.yml
I changed the bblfsh and drivers versions to latest because we were trying to avoid any of the v2 changes, but this is not necessary anymore.
=> Update staging to gitbase 0.16.0

Makefile
fix #206
as its dependency https://github.com/src-d/ci/pull/84 was already merged
=> Remove outdated TODO

docker-compose.yml
Gitbase `latest` tag points to a RC, and bblfsh 2.8.0 exits when you try to install a language that is already installed.
Now that gitbase-web is stable, let's play it safe and set fixed versions!
=> Use fixed versions in docker-compose

.helm-staging.yml, .travis.yml, docker-compose.yml, docs/CONTRIBUTING.md
- Use bblfsh `-drivers` image in `docker-compose` and dev. docs.
- Bring back the `latest` bblfshd to travis to detect problems with new releases.
- Update staging to 2.9.0
=> Update to bblfsh 2.9, use -drivers image

frontend/src/App.js
Fix #258.
In gitbase 0.17 UAST is no longer an array, it's a blob that serializes the nodes.
So we can't use `ARRAY_LENGTH`.
Maybe we should come up with a catchy example using xpath, but for now let's remove the failing example.
=> Remove example with ARRAY_LENGTH

cmd/gitbase-web/main.go
After an idle time of >60s the next query was always failing with `Query Failed - invalid connection`.
Apparently the problem is that the connection was close on gitbase's end and we still kept it open on our side.
More context in this thread:
https://github.com/go-sql-driver/mysql/issues/674#issuecomment-345661869
=> [HOTFIX] Set DB conn reuse timeout

frontend/src/App.js, frontend/src/components/TabbedResults.js, frontend/src/index.js
Fix #265.
With this change the cancel button is grayed out, and if you go to the console you'll see the reason and a link to the supported browser versions.
=> Disable cancel button for older browsers

Gopkg.lock, Gopkg.toml, vendor/gopkg.in/src-d/go-cli.v0/log.go
Update to make use of `choice` in log options, https://github.com/src-d/go-cli/pull/9.
Before:
```
Usage:
gitbase-web [OPTIONS] serve [serve-OPTIONS]
starts serving the application
Help Options:
-h, --help                  Show this help message
[serve command options]
--host=             IP address to bind the HTTP server (default: 0.0.0.0) [$GITBASEPG_HOST]
--port=             Port to bind the HTTP server (default: 8080) [$GITBASEPG_PORT]
--server=           URL used to access the application in the form 'HOSTNAME[:PORT]'. Leave it unset to allow connections from
any proxy or public address [$GITBASEPG_SERVER_URL]
--db=               gitbase connection string. Use the DSN (Data Source Name) format described in the Go MySQL Driver docs: …
```
=> Update go-cli dependency

Dockerfile
Part of #248.
Updates the dockerfile to remove packages not needed after bblfsh/client-go was updated to v3.
=> Update dockerfile dependencies for bblfsh client-go v3

.drone.yml, .helm-staging.yml
Hence we fix the old defaults to avoid changes in our deployment. The
main thing is to fix service type to node port as it is required by GCE
ingress.
Signed-off-by: Rafael Porres Molina <rafa@sourced.tech>
=> Service defaults have changed in upstream chart

.travis.yml, docker-compose.yml
PR to the still unmerged `gitbase-0.18` branch, to see if tests keep working.
=> Update gitbase to v0.18.0-beta.3

.helm-staging.yml, docker-compose.yml
Update bblfsh to 2.10.0 in docker compose and staging deployment. For staging I also updated the drivers to the versions included in the `v2.10.0-drivers` docker image.
=> Update to bblfshd 2.10.0

frontend/src/App.less, frontend/src/components/HelpModal.js, frontend/src/components/HelpModal.less, frontend/src/components/QueryBox.js, frontend/src/variables.less
Fix #293.
@ricardobaeta please comment on icon placement. Also, it would be good if you could provide it as `svg` instead of `png`, like the rest of the icons.
Although it feels to me it is not too subtle for a help icon... One thing we could change: remove this keyboard icon, and have the top-right 'Help' button we already have open a modal with the text:
```
For a reference of gitbase SQL, please read https://docs.sourced.tech/gitbase
Keyboard shortcuts:
[table]
```
=> Add keyboard shortcuts modal help

frontend/src/components/HelpModal.js
The link made in #298 should have had the same `target` as the ones in the sidebar.
=> Set help link target to blank

.travis.yml
Adds names to each travis job.
Plus it merges two jobs. `make packages` is just checking if the project compiles, it can be merged with the unit tests to avoid waiting for another VM.
=> Add description to the travis jobs

README.md, docker-compose.yml
Related to the empathy-session.
- README: fix `docker-compose up` command description.
- docker-compose.yml: remove `GITBASE_UNSTABLE_SQUASH_ENABLE: "true"` line. This is the default behavior since gitbase v0.14.0. Make the directory `./repos` the default one if there's no one set.
=> Update docker-compose.yml and README

frontend/config-overrides.js, frontend/craco.config.js, frontend/package.json, frontend/src/App.js, frontend/src/components/CodeViewer.js, frontend/src/components/HelpModal.js, frontend/src/components/QueryBox.js, frontend/src/components/SampleQueries.js, frontend/src/components/Schema.js, frontend/src/components/Sidebar.js, frontend/src/components/TabbedResults.js, frontend/src/components/UASTViewer.js, frontend/src/components/__snapshots__/ResultsTable.test.js.snap, frontend/src/setupProxy.js, frontend/yarn.lock
This PR replaces #361.
I followed the migration guide from https://github.com/facebook/create-react-app/releases/tag/v2.0.3.
react-app-rewired does not fully support Create React App 2.0. We used react-app-rewired for SVG loading, and less support. 
Create React App 2.x already supports SVGs.
For less I installed https://github.com/sharegate/craco and https://github.com/FormAPI/craco-less, which seems to be a popular alternative to react-app-rewired.
=> [Update create-react-app to 2.x

frontend/src/components/UASTViewer.js, frontend/src/components/UASTViewerPane.js
Closes #402.
There are two problems:
1. `UASTViewerPane` checks only for `flatUast` and not
`initialFlatUast`. This means that it can work only when the
`uast-viewer` is used in *controlled mode*. This has been fixed by
checking `flatUast` first and then fallback to `initialFlatUast`.
2. `UASTViewer` component needs to be in *uncontrolled mode*, so it
needs to use `initialFlatUast`. This has ben fixed by renaming
`flatUast` into `initialFlatUast`.
=> Fixes initialization of `UASTViewer`
