server/handler/uast.go, server/router.go
Part of #2.
Depends on #8, the only new commit is 9a4da5b.
=> Mock uast endpoints

frontend/src/App.js, frontend/src/App.less, frontend/src/components/Loader.js, frontend/src/components/Loader.less, frontend/src/components/QueryBox.js, frontend/src/components/QueryBox.less, frontend/src/components/ResultsTable.js, frontend/src/components/ResultsTable.less, frontend/src/index.js
Part of #4, depends on #16 & #17.
The only new commit is f0c9249.
Adds basic layout and style improvements:
- Remove debug box
- Show error messages
- Show loading animation and disable RUN button while loading.
-------------
-------------
-------------
=> Basic UI improvements

Makefile, cmd/gitbase-playground/main.go, docs/quickstart.md, public/index.html, public/secondary.html
fix #5
Front assets will be served by the single binary
=> Add frontend assets into single binary

server/handler/static_files.go
Nonexistent files under `/static` folder will be served as `404` instead of serving `/index.html`
=> Fix static 404

docs/rest-api.md, frontend/src/api.js, server/handler/query.go, server/handler/schema.go, server/handler/schema_integration_test.go, server/handler/tables.go, server/handler/tables_integration_test.go, server/router.go, server/serializer/serializers.go
Fix: #40
actually, the title of the issue and description are different. I implemented it according to the description.
=> tables endpoint should return complete schema

docs/rest-api.md, frontend/package.json, frontend/src/App.js, frontend/src/api.js, frontend/src/components/QueryBox.js, frontend/src/setupTests.js, frontend/yarn.lock, server/handler/export.go, server/handler/export_integration_test.go, server/router.go
Based on #55
Fix: #42 
The button opens new tab and endpoint streams csv to response.
=> Add Export: backend and frontend

frontend/src/App.js, frontend/src/components/SampleQueries.js, frontend/src/components/Schema.js, frontend/src/components/Schema.less, frontend/src/components/Sidebar.js
Based on #50
Fix: #22 
Fix: #43
Examples aren't real. We need a list of examples from the product team.
=> handle clicks on schema and examples

.travis.yml, Makefile, docs/CONTRIBUTING.md, server/handler/common_test.go, server/handler/export_integration_test.go, server/handler/query_integration_test.go, server/handler/query_uast_integration_test.go, server/handler/schema_integration_test.go, server/handler/uast_integration_test.go
=> Add integration tests to coverage report

server/handler/query.go, server/handler/query_uast_integration_test.go, server/handler/uast.go
=> Modify uast nodes the same way as babelfish dashboard

Gopkg.lock, Gopkg.toml, server/handler/common_test.go, server/handler/export.go, server/handler/export_integration_test.go, server/handler/export_test.go, server/handler/query.go, server/handler/query_integration_test.go, server/handler/query_test.go, server/handler/query_uast_integration_test.go, server/handler/schema_integration_test.go, server/handler/schema_test.go, server/handler/uast_integration_test.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/LICENSE, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/argument.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/driver.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/expectations.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/expectations_before_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/expectations_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/result.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/rows.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/rows_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/sqlmock.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/sqlmock_go18.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/statement.go, vendor/gopkg.in/DATA-DOG/go-sqlmock.v1/util.go
Part of #32.
Also contains a couple of fixes for bugs uncovered by the new tests.
=> More unit tests

docker-compose.yml, docs/quickstart.md
=> Update docker-compose to a fixed bblfshd version

frontend/src/App.js
Fixes #65.
Latest gitbase release brings some syntax changes
=> Update default query for gitbase v0.12.1-rc1

frontend/src/App.js, frontend/src/components/HistoryTable.js, frontend/src/components/HistoryTable.less, frontend/src/components/TabbedResults.js, frontend/src/state/query.js
=> implement history tab

.drone.yml, .helm-staging.yml, .travis.yml
Fixes #74 
The file is based on the [one in code-annotation](https://github.com/src-d/code-annotation/blob/master/.drone.yml).
With the new configuration drone will create, push, and deploy to staging a new docker image for each commit in master. It will also create and push when a new tag is created.
=> Add .drone.yml file

.drone.yml
Signed-off-by: Rafael Porres Molina <rafa@sourced.tech>
=> Use current helm release name

frontend/src/components/QueryBox.less
=> Fix scroll for query box in firefox

frontend/src/App.js, frontend/src/App.less, frontend/src/components/Sidebar.js, frontend/src/components/Sidebar.less
=> Make the sidebar collapsable

frontend/src/App.js, frontend/src/components/QueryBox.less, frontend/src/components/TabbedResults.js
=> Suspend inactive tabs

server/handler/query.go, server/handler/query_test.go
=> smarter add limit

frontend/src/App.js, frontend/src/api.js, frontend/src/components/HistoryTable.js, frontend/src/components/HistoryTable.less, frontend/src/components/QueryBox.js, frontend/src/components/TabbedResults.js, frontend/src/state/query.js
Fix #78 
Based on #79 
I'm super confused that results and the box with the time are in different places. It looks like they are disconnected, so I implemented them like that. Box shows information about the last result. But I'm not sure it's correct.
=> Inform the user of the elapsed time

frontend/src/App.js, frontend/src/components/ResultsTable.js, frontend/src/components/ResultsTable.less, frontend/src/components/__snapshots__/ResultsTable.test.js.snap, frontend/src/setupTests.js, frontend/src/utils/bootstrap.js
=> Set styling for results table

.helm-staging.yml, docker-compose.yml
=> Set gitbase squash enable env var

frontend/src/App.js, frontend/src/components/SampleQueries.js, frontend/src/components/Sidebar.js
=> Execute the first example on page load

frontend/src/components/TabbedResults.js, frontend/src/components/TabbedResults.less
=> Hide history tab when table is empty

frontend/src/components/TabbedResults.js, frontend/src/components/TabbedResults.less
Part of #44, depends on #100.
With this change the sql query inside the results is made one line truncated by an ellipsis.
=> Issue 44 truncate sql

frontend/package.json, frontend/src/components/CodeViewer.js, frontend/yarn.lock
=> Show empty div instead of empty Node when parsing fails

frontend/src/api.js, frontend/src/components/CodeViewer.js, frontend/src/components/TabbedResults.js
=> Add x-path query and settings panel to uast viewer pane

.helm-staging.yml
=> remove typescript driver from staging because it is alpha

.helm-staging.yml
=> Add siva-java repo to staging deployment

frontend/src/components/CodeViewer.js, frontend/src/components/CodeViewer.less, frontend/src/utils/bootstrap.js, frontend/src/variables.less
Part of #48.
The code here continues the work done in #140, adding styles for the new xpath query input introduced in #128.
The changes to `UASTViewerPane` are small and localized, I don't expect this PR to be very difficult to merge with #135.
=> Style for the modal UAST panel query

server/handler/uast.go
=> sort list of languages

frontend/package.json, frontend/yarn.lock
tested only on Java code. There are might be some problems with other languages due to lack/wrong position.
=> enable pane scrolling on code-uast viewer

frontend/src/components/Schema.less
=> fix schema hover

frontend/src/components/CodeViewer.js, frontend/src/components/UASTViewerPane.js
Based on #135
Fix: #161
Custom server removed only from frontend as requested by the issue. If you think it should be removed from backend too, please let me know.
=> Remove server input

.travis.yml, README.md, cmd/gitbase-playground/main.go, docker-compose.yml, docs/CONTRIBUTING.md, docs/quickstart-manually.md, server/handler/common_integration_test.go
gitbase v0.14.0-rc1 changed user from `gitbase` to `root`.
Travis is currently failing on master: https://travis-ci.org/src-d/gitbase-playground/jobs/398254777
=> change default gitbase user to root

frontend/src/App.js
=> Retry loading language list

cmd/gitbase-playground/main.go, docs/CONTRIBUTING.md, frontend/public/index.html, server/handler/static_files.go
Fix: #165 
I ignore error if a wrong base64 was provided. Please let me know if you think we need to check it on the start of the server and doesn't allow it to start/write error somewhere.
=> Add configurable small HTML snippet to the frontend

frontend/src/components/QueryBox.js, frontend/src/components/QueryBox.less
Fix: #103
It might look a bit strange when the first line of query is too long but I don't see how to make it better (from UI point of view).
=> add help link

frontend/src/App.js
Fix #76.
This PR sets the default queries proposed in the issue conversation.
ping @smola @ajnavarro, in case you want to chime in.
=> Set the example queries

.travis.yml
=> Add travis test for FOOTER_HTML

server/handler/uast.go, server/handler/uast_integration_test.go
Fix: #179
It's not easy to come up with test case when filter would fail with another error.
=> Use tools.ErrInvalidArgument

docs/rest-api.md, frontend/src/components/ResultsTable.js, frontend/src/components/ResultsTable.less, server/handler/query.go, server/handler/query_test.go, server/serializer/serializers.go
Fix #117.
This PRs adds a small message with the forced limit near the table pagination controls:
ping @ricardobaeta, in case you want to take a look.
=> Show limit

.helm-staging.yml
Signed-off-by: Maxim Sukharev <maxim@sourced.tech>
=> bump gitbase to v0.14.0 on staging

server/handler/query.go, server/handler/query_integration_test.go, server/handler/query_test.go
Fix #189.
The first commit is just a refactor and tests, the fix is in the second one.
=> Fix value for float columns

frontend/package.json, frontend/yarn.lock
to benefit from the recent performance improvements
=> bump uast-viewer

frontend/src/App.js
Number of functions per file for Go language @HEAD 
```sql
SELECT files.repository_id, files.file_path,
ARRAY_LENGTH(UAST(
files.blob_content,
LANGUAGE(files.file_path, files.blob_content),
'//*[@roleFunction and @roleDeclaration]'
)) as functions
FROM files
NATURAL JOIN refs
WHERE 
LANGUAGE(files.file_path,files.blob_content) = 'Go'
AND refs.ref_name = 'HEAD'
```
=> Add one more query example

server/handler/version.go, server/router.go, server/router_test.go, server/serializer/serializers.go, server/service/common.go, server/testing/common.go
=> Version endpoint should include versions of dependencies

.helm-staging.yml
Part of #183, the version UDF was added in this gitbase release.
=> Update gitbase to v0.15.0 in staging

README.md
=> Doc: add cleanup instructions for docker-compose scenario

frontend/src/App.js
=> disable example autorun

README.md
Motivated by a question on how to add a password to the connection string.
=> Add link to mysql dsn reference in readme

docker-compose.yml
Fix #197.
Without this you couldn't transform code to UAST in the UI.
=> Add bblfsh url env var in docker compose

frontend/package.json, frontend/src/index.js
=> Use abortcontroller polyfill in browser code

.helm-staging.yml
Signed-off-by: Maartje Eyskens <maartje@eyskens.me>
=> Update bblfshdServer in helm staging

server/handler/query.go, server/handler/query_test.go
=> Fix corner case in query addLimit

Gopkg.lock, Makefile, README.md, cmd/gitbase-web/main.go, docker-compose.yml, docs/CONTRIBUTING.md, server/handler/query.go
=> Use go-log lib

.helm-staging.yml
Signed-off-by: Rafael Porres Molina <rafa@sourced.tech>
=> added node selector

docs/rest-api.md, frontend/package.json, frontend/src/api.js, frontend/src/components/CodeViewer.js, frontend/src/components/ParseModeSwitcher.js, frontend/src/components/ParseModeSwitcher.test.js, frontend/src/components/UASTViewerPane.js, frontend/src/components/__snapshots__/ParseModeSwitcher.test.js.snap, frontend/src/setupTests.js, frontend/yarn.lock, server/handler/uast.go, server/handler/uast_integration_test.go
Part of #248.
Adds a selector to choose the UAST transformation mode.
=> UAST mode selector

.drone.yml
Changed drone to use the new chart version ( was updated to 0.4.0)
Signed-off-by: David Riosalido <driosalido@sourced.tech>
=> gitbase-web chart updated to 0.4.0

.helm-defaults.yml
Somehow I forgot to include it in #296.
=> Use gitbase v0.18.0 in staging deployment

Makefile
caused by https://github.com/src-d/gitbase-web/pull/250
=> Fix way the command is run

README.md, cmd/gitbase-web/main.go
=> Adds possibility to configure conn max lifetime

server/handler/query.go, server/handler/query_test.go, server/service/common.go, server/testing/common.go
=> Modifies killQuery in order to use the connection id

.helm-defaults.yml, docker-compose.yml
Includes the driver versions included in `v2.11.6-drivers`.
=> Update to bblfshd 2.11.6

Makefile
=> Modifies Makefile in order to include bin for OSX and Windows

server/handler/query.go
Fix #357.
See issue for details on the bug. This PR basically makes bigger the "wrapper logic" of killing the connection on context cancellation from (`QueryContext`) to (`QueryContext` + rows processing).
=> Kill queries also after the rows start streaming

frontend/package.json, frontend/src/components/UASTViewer.js, frontend/src/components/UASTViewerPane.js, frontend/yarn.lock
fix: #304
Signed-off-by: Maxim Sukharev <max@smacker.ru>
=> update uast-viewer to v0.4.0

frontend/src/components/CodeViewer.js
fix: #354
Signed-off-by: Maxim Sukharev <max@smacker.ru>
=> fix: switching between uast modes returns inconsistent results

.drone.yml, .travis.yml
=> Updates go version 1.11 -> 1.12

.helm-defaults.yml, docker-compose.yml
=> Update bblfshd to v2.12.1

.drone.yml
Signed-off-by: Maartje Eyskens <maartje@eyskens.me>
=> Deploy the Helm chart from the new stable charts repo
